#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Google Cloud OAuth 設定，供本機一次性 Keep 匯入腳本呼叫
# Sheets API / Drive API 使用。這是個人單機使用，不涉及 CI，不使用
# set_secret/set_var；.env 也不需要，憑證本身就是 credentials.json 檔案。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CREDENTIALS_PATH="$PROJECT_DIR/credentials.json"

# _to_native_path converts a possibly-Windows path (C:\...) to one this
# Git-Bash shell can operate on directly, using cygpath if available.
_to_native_path() {
  local p="$1"
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -u "$p" 2>/dev/null || printf '%s' "$p"
  else
    printf '%s' "$p"
  fi
}

banner "Google Cloud 設定：讓匯入腳本能呼叫 Sheets / Drive API"

stage "建立 Google Cloud 專案"
say "先建立一個專屬這個匯入工具用的 Google Cloud 專案（免費，不會產生費用，除非你自己另外開啟計費相關進階功能）。"
open_url "https://console.cloud.google.com/projectcreate"
step "「專案名稱」隨意填，例如 personal-data-system-import。"
step "位置（機構）維持預設就好，不用改。"
step "按下「建立」，等右上角出現建立完成的通知。"
step "建立完成後，確認畫面最上方的專案選單已經切換到這個新專案（之後每個階段都要維持選在同一個專案）。"
pause "專案建立好、也確認已選取了嗎？按 Enter 繼續。"

stage "啟用 Google Sheets API"
say "匯入腳本要寫資料進 Google Sheets，需要先啟用這個 API。"
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com"
step "確認網頁上方的專案還是剛剛那個。"
step "點藍色的「啟用」(Enable) 按鈕，等它跑完（通常幾秒鐘）。"
pause "看到已啟用（或按鈕變成「管理」）了嗎？按 Enter 繼續。"

stage "啟用 Google Drive API"
say "匯入腳本要把圖片上傳到 Google Drive，需要啟用這個 API。"
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
step "一樣確認專案正確，點「啟用」。"
pause "啟用完成了嗎？按 Enter 繼續。"

stage "設定 OAuth 同意畫面"
say "這是 Google 要求的授權說明頁設定，因為只有你自己用，選「測試」模式即可，不需要送 Google 審核、不會有其他人看到這個畫面。"
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "使用者類型選「外部」(External)，按建立。"
step "應用程式名稱隨意填，例如「個人資料整理系統匯入工具」。"
step "使用者支援電子郵件、開發人員聯絡資訊都填你自己的 Gmail。"
step "其餘欄位留空，一路按「儲存並繼續」直到「範圍」頁，範圍頁不用加任何項目，直接「儲存並繼續」。"
step "到「測試使用者」頁，按「+ ADD USERS」，把你自己的 Gmail 加進去，儲存。"
step "最後「回到資訊主頁」即可，不需要按「發布應用程式」。"
pause "同意畫面設定完成、也把自己加為測試使用者了嗎？按 Enter 繼續。"

stage "建立 OAuth 用戶端 ID 並下載憑證"
say "這一步產生匯入腳本實際要用的憑證檔案。"
open_url "https://console.cloud.google.com/apis/credentials"
step "點上方「+ 建立憑證」(CREATE CREDENTIALS) → 選「OAuth 用戶端 ID」。"
step "應用程式類型一定要選「桌面應用程式」(Desktop app)。"
step "名稱隨意填，例如 keep-import-desktop，按「建立」。"
step "跳出視窗後按「下載 JSON」，檔案通常會存到你的「下載」資料夾，檔名類似 client_secret_xxxxxxxx.json。"
pause "JSON 檔案下載完成了嗎？按 Enter 繼續。"

stage "把憑證檔案移進專案資料夾"
say "現在把剛剛下載的 JSON 檔案，複製一份到專案資料夾裡並改名成 credentials.json，方便匯入腳本讀取。"
say "專案資料夾位置：$PROJECT_DIR"
DOWNLOADED_JSON=""
ask DOWNLOADED_JSON "貼上剛剛下載的 JSON 檔案完整路徑（例如 C:\\Users\\ASUS\\Downloads\\client_secret_xxxx.json）："
SRC_PATH="$(_to_native_path "$DOWNLOADED_JSON")"
if [[ ! -f "$SRC_PATH" ]]; then
  warn "找不到這個檔案：$SRC_PATH"
  warn "請確認路徑是否貼對，或手動把檔案複製到 $CREDENTIALS_PATH 後再重跑這個階段。"
else
  cp "$SRC_PATH" "$CREDENTIALS_PATH"
  printf '  %s✓ 已複製到%s %s\n' "$GREEN" "$RESET" "$CREDENTIALS_PATH"
fi

GITIGNORE_PATH="$PROJECT_DIR/.gitignore"
touch "$GITIGNORE_PATH"
for entry in "credentials.json" "token.json"; do
  if ! grep -qxF "$entry" "$GITIGNORE_PATH" 2>/dev/null; then
    printf '%s\n' "$entry" >> "$GITIGNORE_PATH"
    printf '  %s✓ 已加入 .gitignore%s：%s\n' "$GREEN" "$RESET" "$entry"
  fi
done
pause "按 Enter 繼續到最後的驗證。"

stage "驗證憑證檔案"
say "最後檢查一下檔案內容格式是否正確（只檢查有沒有必要欄位，不會印出實際的金鑰內容）。"
if [[ -f "$CREDENTIALS_PATH" ]]; then
  if grep -q '"client_id"' "$CREDENTIALS_PATH" && grep -q '"client_secret"' "$CREDENTIALS_PATH"; then
    printf '  %s✓ credentials.json 格式看起來正確（含 client_id / client_secret）%s\n' "$GREEN" "$RESET"
  else
    warn "credentials.json 存在，但沒看到 client_id / client_secret 欄位，請確認下載的檔案類型是不是「桌面應用程式」的 OAuth 用戶端。"
    SKIPPED+=("重新確認 credentials.json 內容（$CREDENTIALS_PATH）")
  fi
else
  warn "還沒找到 $CREDENTIALS_PATH，請重跑上一階段。"
  SKIPPED+=("把憑證檔案放到 $CREDENTIALS_PATH")
fi

finish
note "接下來 Node.js 匯入腳本會用 $CREDENTIALS_PATH 這個檔案第一次執行時跳出瀏覽器登入頁，登入同意後會在專案資料夾產生 token.json，之後就不用重複登入。"
